version: '3'
services:
  appwrite:
    image: appwrite/appwrite:1.3.8
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./appwrite:/usr/src/code/appwrite:rw
    entrypoint: install
